FROM node:14.16.0-alpine3.13 AS build-prod
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_API_URL=http://165.22.43.126:3001/api
RUN npm run build

FROM nginx:1.12-alpine
COPY --from=build-prod /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]